### ISSUE TITLE
Make the sign up for newsletter sticky

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/insights.ubuntu.com#251] opened 2018-03-14 14:27 UTC
Can you make the sign up for newsletter sticky at the top of the side column of any blog post. (under the top message but sticking to the top of the browser when scrolling down.

**Comment by anthonydillon** [comment] 2018-03-18 22:57
This is a duplicate of this issue https://github.com/canonical-websites/insights.ubuntu.com/issues/258.

Closing this one as the other is already triage.

**Closed by anthonydillon** 2018-03-18 22:57 UTC
